### ISSUE TITLE
Compilation failed with higher version of g++

### ISSUE THREAD

**Issue by enzoleo** [OpenTimer/OpenTimer#41]
With `g++10.2` the compilation will fail due to the following lines. These lines appear in multiple files and induce duplicate declaration.
```c++
namespace std {
  namespace filesystem = experimental::filesystem;
};
```
I believe with higher version of `g++` the namespace `std::filesystem` has ready been declared in the standard header `<filesystem>`. Replace all `std::experimental::filesystem` with `std::filesystem` and `<experimental/filesystem>` with `<filesystem>` the problem can be resolved (but this workaround does not consider compatibility).

**Comment by tsung-wei-huang** [comment]
Yes, I will change it later on - for now, feel free to modify that namespace to get rid of the compilation error.

**Comment by mooredan** [comment]
Me too. I'm on a Pop!_OS 20.10 system with c++ (Ubuntu 10.2.0-13ubuntu1) 10.2.0

These sed commands got this compiling:

```
sed -i -e 's:experimental/filesystem:filesystem:' ./ot/parser-spef/parser-spef.hpp ./ot/shell/prompt.hpp ./ot/headerdef.hpp ./ot/utility/os.hpp ./ot/utility/tokenizer.hpp

sed -i -e 's/std::experimental::filesystem/std::filesystem/' ./ot/parser-spef/parser-spef.hpp

sed -i -e 's/experimental::filesystem/std::filesystem/' ./ot/shell/prompt.hpp ./ot/utility/os.hpp ./ot/utility/tokenizer.hpp

```
I can provide a pull request, but I suspect this isn't the correct way to address this as it might cause  backward compatibility issue.
