### ISSUE TITLE
[FPGA application]. Does the opentimer support FPGA STA?

### ISSUE THREAD

**Issue by xinlnix** [OpenTimer/OpenTimer#43]
Does the opentimer supports FPGA STA? Or supports multi FPGA system level STA?.
Is that easy for us to enhance the feather.
Thanks your patient reply in advance.

**Comment by tsung-wei-huang** [comment]
No, OpenTimer doesn't support FPGA for now :)

**Comment by xinlnix** [comment]
thanks a lot

**Comment by xinlnix** [comment]
If I want to enhance it to support FPGA, what's the  difficult part of it. And what's the difference between FPGA and ASIC in STA?
