### ISSUE TITLE
required libstdc++ files not found

### ISSUE THREAD

**Issue by spr13** [OpenTimer/OpenTimer#6]
Hello Tsung-Wei

I installed OpenTimer without any issues. But I do have a problem once I run it:
```
 $ ./ot-shell
./ot-shell: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./ot-shell)
./ot-shell: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./ot-shell)
./ot-shell: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./ot-shell)
./ot-shell: /lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by ./ot-shell)
./ot-shell: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./ot-shell)
./ot-shell: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./ot-shell)
```
I also tried 
`make test`
 All test failed.

I'm not sure what could have gone wrong since OpenTimer installed without any error.

```
The system is: Linux - 3.10.0-693.11.6.el7.x86_64 - x86_64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: /bin/cc 
Build flags: 
Id flags:  

The output was:
0


Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"

The C compiler identification is GNU, found in "/home/tetrivis/Documents/Qflow/OpenTimer/OpenTimer/build/CMakeFiles/3.12.0/CompilerIdC/a.out"

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler: /usr/local/gcc/7.3.0/bin/g++ 
Build flags: 
Id flags:  

The output was:
0
```

Even though the install had no errors I do not think it worked because the lib folder is empty. What should I do?

**Comment by twhuang-uiuc** [comment]
Hi @spr13 , The message says, the linker can find the shared library `/lib64/libstdc++.so.6` but this library belongs to an ***older*** version of GCC than what you used to compile OpenTimer. OpenTimer requires newer `libstdc++` that belongs to newer GCC and the linker must be told to link the new `libstdc++` library.

The simplest way to fix this is to use the `LD_LIBRARY_PATH` environment variable - a colon-separated list of directories where the linker will search for shared library.

```bash
export LD_LIBRARY_PATH=${prefix}/lib:$LD_LIBRARY_PATH
```
Here the `${prefix}` is assumed to contain the directory prefix where your GCC is installed to. In your case it should be `/usr/local/gcc/7.3.0/` (or you need to find it out). So please try this:

```bash
export LD_LIBRARY_PATH=/usr/loca/gcc/7.3.0/:$LB_LIBRARY_PATH
```

And rerun it again.

**Comment by spr13** [comment]
I believe the error could be caused by the library path pointing to the wrong folder.
How would I set up the instalation so that ot-shell can look at /usr/local/gcc/7.3.0/lib64/libstdc++.so.6 instead of /lib64/libstdc++.so.6?

I changed the C complier to path to /usr/local/gcc/7.3.0/bin/gcc and it did not fix the problem.

Thank you for your time

**Comment by spr13** [comment]
Thank you. 
That resolved my issue!
